language: node_js
node_js:
  - 'node'
  - '8'
dist: trusty
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
branches:
  only:
    - 'master'

matrix:
  fast_finish: true

install:
  - npm install
  - npm link

script:
  - npm test
  - mkdir travis
  - cd travis
  - bs init
  - bs export
  - bs pdf --verbose -- --no-sandbox
  